# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.integration_rclone: debug

# Configuration for integration_rclone entry
integration_rclone:
  url: http://0.0.0.0:3000/api/tasks

automation: !include automations.yaml